//
// Category.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Category: JSONEncodable {
    public enum [Visibility]: String { 
        case Facebook = "facebook"
        case Mobile = "mobile"
        case Webstore = "webstore"
        case None = "none"
        case All = "all"
    }
    public var id: Int32?
    public var position: Int32?
    /** The file to be attached. Must be multipart/form-data. The maximum file size is 2 MB.  */
    public var imageSmall: String?
    /** The file to be attached. Must be multipart/form-data. The maximum file size is 2 MB.  */
    public var imageLarger: String?
    public var active: Bool?
    public var createdAt: NSDate?
    public var updatedAt: NSDate?
    /** channels that resource are showed */
    public var visibility: [Visibility]?
    /** I18n fields to categories */
    public var i18n: [I18n]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["image_small"] = self.imageSmall
        nillableDictionary["image_larger"] = self.imageLarger
        nillableDictionary["active"] = self.active
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        nillableDictionary["visibility"] = self.visibility?.encodeToJSON()
        nillableDictionary["i18n"] = self.i18n?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
