//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Customer: JSONEncodable {
    public var id: Int64?
    public var firstname: String?
    public var lastname: String?
    public var active: Bool?
    public var birhday: ISOFullDate?
    public var vat: Int64?
    public var email: String?
    public var phone: String?
    public var company: String?
    public var gender: String?
    public var receivedNewsletter: Bool?
    public var createdAt: NSDate?
    public var updatedAt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["firstname"] = self.firstname
        nillableDictionary["lastname"] = self.lastname
        nillableDictionary["active"] = self.active
        nillableDictionary["birhday"] = self.birhday?.encodeToJSON()
        nillableDictionary["vat"] = self.vat?.encodeToJSON()
        nillableDictionary["email"] = self.email
        nillableDictionary["phone"] = self.phone
        nillableDictionary["company"] = self.company
        nillableDictionary["gender"] = self.gender
        nillableDictionary["received_newsletter"] = self.receivedNewsletter
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
