//
// I18n.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class I18n: JSONEncodable {
    public var locale: String?
    public var name: String?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["locale"] = self.locale
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
