//
// I18nProductSeo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class I18nProductSeo: JSONEncodable {
    public var title: String?
    public var keywords: String?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["keywords"] = self.keywords
        nillableDictionary["description"] = self.description
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
