//
// MetaPartialResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MetaPartialResponse: JSONEncodable {
    public var firstPageUrl: String?
    public var lastPageUrl: String?
    public var nextPageUrl: String?
    public var path: String?
    public var prevPageUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["first_page_url"] = self.firstPageUrl
        nillableDictionary["last_page_url"] = self.lastPageUrl
        nillableDictionary["next_page_url"] = self.nextPageUrl
        nillableDictionary["path"] = self.path
        nillableDictionary["prev_page_url"] = self.prevPageUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
