//
// Options.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Options: JSONEncodable {
    public var id: Int64?
    public var position: Int64?
    public var auxCode: String?
    public var i18n: I18n?
    public var createdAt: NSDate?
    public var updatedAt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["aux_code"] = self.auxCode
        nillableDictionary["i18n"] = self.i18n?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
