//
// Product.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Product: JSONEncodable {
    public enum [Visibility]: String { 
        case Facebook = "facebook"
        case Mobile = "mobile"
        case Webstore = "webstore"
        case None = "none"
        case All = "all"
    }
    public var id: Int64?
    public var sku: String?
    public var manual: String?
    public var urlVideo: String?
    /** channels that resource are showed */
    public var visibility: [Visibility]?
    public var inHomepage: Bool?
    public var isPrefered: Bool?
    public var isDigital: Bool?
    public var urlDigital: String?
    public var isNew: Bool?
    public var i18n: I18nProduct?
    public var active: Bool?
    public var createdAt: NSDate?
    public var updatedAt: NSDate?
    public var expiresAt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["manual"] = self.manual
        nillableDictionary["url_video"] = self.urlVideo
        nillableDictionary["visibility"] = self.visibility?.encodeToJSON()
        nillableDictionary["in_homepage"] = self.inHomepage
        nillableDictionary["is_prefered"] = self.isPrefered
        nillableDictionary["is_digital"] = self.isDigital
        nillableDictionary["url_digital"] = self.urlDigital
        nillableDictionary["is_new"] = self.isNew
        nillableDictionary["i18n"] = self.i18n?.encodeToJSON()
        nillableDictionary["active"] = self.active
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        nillableDictionary["expires_at"] = self.expiresAt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
