//
// CustomersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CustomersAPI: APIBase {
    /**

     - parameter id: (path) ID of customer 
     - parameter includes: (query) Include associated objects within response (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getCustomerById(id id: Int64, includes: [String]? = nil, completion: ((data: [Customer]?, error: ErrorType?) -> Void)) {
        getCustomerByIdWithRequestBuilder(id: id, includes: includes).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /customers/{id}/
     - Returns all customers from the system that the user has access to  ### Includes You can give the following values on includes parameter: `orders, groups` 
     - API Key:
       - type: apiKey APIToken 
       - name: APIKeyHeader
     - examples: [{contentType=application/json, example=[ {
  "firstname" : "John",
  "gender" : "gender",
  "received_newsletter" : true,
  "vat" : 1234567890,
  "active" : true,
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "lastname" : "Doe",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "phone" : "912345678",
  "birhday" : "2",
  "company" : "company",
  "id" : 1,
  "email" : "foobar@foo.com"
}, {
  "firstname" : "John",
  "gender" : "gender",
  "received_newsletter" : true,
  "vat" : 1234567890,
  "active" : true,
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "lastname" : "Doe",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "phone" : "912345678",
  "birhday" : "2",
  "company" : "company",
  "id" : 1,
  "email" : "foobar@foo.com"
} ]}]
     
     - parameter id: (path) ID of customer 
     - parameter includes: (query) Include associated objects within response (optional)

     - returns: RequestBuilder<[Customer]> 
     */
    public class func getCustomerByIdWithRequestBuilder(id id: Int64, includes: [String]? = nil) -> RequestBuilder<[Customer]> {
        var path = "/customers/{id}/"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "includes": includes
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Customer]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**

     - parameter includes: (query) Include associated objects within response (optional)
     - parameter limit: (query) max records to return (optional)
     - parameter orderBy: (query) Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60;  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getCustomers(includes includes: [String]? = nil, limit: Int32? = nil, orderBy: [String]? = nil, completion: ((data: [Customer]?, error: ErrorType?) -> Void)) {
        getCustomersWithRequestBuilder(includes: includes, limit: limit, orderBy: orderBy).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /customers
     - Returns all customers from the system that the user has access to  ### Includes You can give the following values on includes parameter: `orders, groups` 
     - API Key:
       - type: apiKey APIToken 
       - name: APIKeyHeader
     - examples: [{contentType=application/json, example=[ {
  "firstname" : "John",
  "gender" : "gender",
  "received_newsletter" : true,
  "vat" : 1234567890,
  "active" : true,
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "lastname" : "Doe",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "phone" : "912345678",
  "birhday" : "2",
  "company" : "company",
  "id" : 1,
  "email" : "foobar@foo.com"
}, {
  "firstname" : "John",
  "gender" : "gender",
  "received_newsletter" : true,
  "vat" : 1234567890,
  "active" : true,
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "lastname" : "Doe",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "phone" : "912345678",
  "birhday" : "2",
  "company" : "company",
  "id" : 1,
  "email" : "foobar@foo.com"
} ]}]
     
     - parameter includes: (query) Include associated objects within response (optional)
     - parameter limit: (query) max records to return (optional)
     - parameter orderBy: (query) Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60;  (optional)

     - returns: RequestBuilder<[Customer]> 
     */
    public class func getCustomersWithRequestBuilder(includes includes: [String]? = nil, limit: Int32? = nil, orderBy: [String]? = nil) -> RequestBuilder<[Customer]> {
        let path = "/customers"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "includes": includes,
            "limit": limit?.encodeToJSON(),
            "order_by": orderBy
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Customer]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
