//
// OrdersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OrdersAPI: APIBase {
    /**

     - parameter id: (path) ID of customer 
     - parameter includes: (query) Include associated objects within response (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOrderById(id id: Int64, includes: [String]? = nil, completion: ((data: [Order]?, error: ErrorType?) -> Void)) {
        getOrderByIdWithRequestBuilder(id: id, includes: includes).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /orders/{id}/
     - Returns all orders from the system that the user has access to  ### Includes You can give the following values on includes parameter: `products, customers` 
     - API Key:
       - type: apiKey APIToken 
       - name: APIKeyHeader
     - examples: [{contentType=application/json, example=[ {
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "name" : "John Doe",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "id" : 1
}, {
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "name" : "John Doe",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "id" : 1
} ]}]
     
     - parameter id: (path) ID of customer 
     - parameter includes: (query) Include associated objects within response (optional)

     - returns: RequestBuilder<[Order]> 
     */
    public class func getOrderByIdWithRequestBuilder(id id: Int64, includes: [String]? = nil) -> RequestBuilder<[Order]> {
        var path = "/orders/{id}/"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "includes": includes
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Order]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**

     - parameter includes: (query) Include associated objects within response (optional)
     - parameter limit: (query) max records to return (optional)
     - parameter orderBy: (query) Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60;  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOrders(includes includes: [String]? = nil, limit: Int32? = nil, orderBy: [String]? = nil, completion: ((data: [Order]?, error: ErrorType?) -> Void)) {
        getOrdersWithRequestBuilder(includes: includes, limit: limit, orderBy: orderBy).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /orders
     - Returns all orders from the system that the user has access to  ### Includes You can give the following values on includes parameter: `products, customers` 
     - API Key:
       - type: apiKey APIToken 
       - name: APIKeyHeader
     - examples: [{contentType=application/json, example=[ {
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "name" : "John Doe",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "id" : 1
}, {
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "name" : "John Doe",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "id" : 1
} ]}]
     
     - parameter includes: (query) Include associated objects within response (optional)
     - parameter limit: (query) max records to return (optional)
     - parameter orderBy: (query) Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60;  (optional)

     - returns: RequestBuilder<[Order]> 
     */
    public class func getOrdersWithRequestBuilder(includes includes: [String]? = nil, limit: Int32? = nil, orderBy: [String]? = nil) -> RequestBuilder<[Order]> {
        let path = "/orders"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "includes": includes,
            "limit": limit?.encodeToJSON(),
            "order_by": orderBy
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Order]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
